### PR TITLE
Fixes for Inventory packets

### PR DESCRIPTION
**Pull request by phoshp**
This fixes a lot of bugs with inventories

Source: [gophertunnel](https://github.com/Sandertv/gophertunnel/blob/f15f2e1f69a58531150cd0cb3419dbddadefd5fa/minecraft/protocol/item.go#L12)

### CODE REVIEW

**Comment by phoshp** [comment]
why?

**Comment by bundabrg** [comment]
Sorry I don't remember closing this at all. I wonder if the branch was deleted when it got merged. Are you able to create a new pr?

**Comment by bundabrg** [comment]
Or better open one on the parent repo as my changes were all merged.

**Comment by phoshp** [comment]
oh okey

**Pull request closed without merging**
